@startmindmap

!define RECTANGLE class


* <color:DarkSlateGray>马克思主义的基本立场</color>
** <color:MidnightBlue>马克思主义的基本立场是观察、分析和解决问题的根本立足点和出发点。</color>
*** <color:DarkSlateGray>以无产阶级的解放和全人类的解放为己任</color>
*** <color:DarkSlateGray>以人的自由全面发展为美好目标</color>
*** <color:DarkSlateGray>以人民为中心，坚持一切为了人民，一切依靠人民，全心全意为人民谋福利</color>

* <color:DarkSlateGray>量变质变规律</color>
** <color:MidnightBlue>量变</color>
*** <color:DarkSlateGray>事物数量的增减和组成要素排列次序的变动</color>
**** <color:Black>保持事物的质的相对稳定性的不显著变化</color>
**** <color:Black>体现了事物发展渐进过程的连续性</color>
** <color:MidnightBlue>质变</color>
*** <color:DarkSlateGray>事物性质的根本变化</color>
**** <color:Black>事物由一种质态向另一种质态的飞跃</color>
**** <color:Black>体现了事物发展渐进过程和连续性的中断</color>
** <color:MidnightBlue>量变和质变的辩证关系</color>
*** <color:DarkSlateGray>量变是质变的必要准备</color>
**** <color:Black>任何事物的变化都有一个量变的积累过程，没有量变的积累，质变就不会发生</color>
*** <color:DarkSlateGray>质变是量变的必然结果，并为新的量变开辟道路</color>
**** <color:Black>单纯的量变不会永远持续下去，量变到达一定程度必然引起质变</color>
*** <color:DarkSlateGray>量变和质变是相互渗透的</color>
**** <color:Black>在总的量变过程中有阶段性和局部性的部分质变</color>
**** <color:Black>在质变过程中也有旧质在量上的收缩和新质在量上的扩张</color>
*** <color:DarkSlateGray>量变和质变是相互依存，相互贯通的</color>
**** <color:Black>量变引起质变，在新质的基础上，事物又开始新的量变，如此交替循环，构成了事物的发展过程</color>
**** <color:Black>量变质变规律体现了事物发展的渐近性和飞跃性的同一</color>
*** <color:DarkSlateGray>方法论意义</color>
**** <color:Black>当事物发展处在量变阶段时，要踏踏实实做好日常工作，为未来重大改变做准备</color>
**** <color:Black>当质变来临的时候，要果断地抓住机遇，促成质变，使工作迈上新台阶</color>

* <color:DarkSlateGray>实践对认识的决定作用（实践是认识的基础）</color>
** <color:MidnightBlue>实践是认识的来源</color>
** <color:MidnightBlue>实践是认识发展的动力</color>
** <color:MidnightBlue>实践是认识的目的</color>
** <color:MidnightBlue>实践是检验认识真理性的唯一标准</color>
** <color:MidnightBlue>认识对实践有指导作用</color>

* <color:DarkSlateGray>生产商品的劳动的二重性学说</color>
** <color:MidnightBlue>具体劳动和抽象劳动</color>
*** <color:DarkSlateGray>具体劳动是指生产一定使用价值的具体形式的劳动</color>
*** <color:DarkSlateGray>抽象劳动是指抛开一切具体形式的、无差别的一般人类劳动，即人的脑力体力的耗费</color>
** <color:MidnightBlue>具体劳动创造商品的使用价值，抽象劳动形成商品的价值</color>
** <color:MidnightBlue>劳动的二重性决定了商品的二要素</color>
** <color:MidnightBlue>具体劳动和抽象劳动的关系</color>
*** <color:DarkSlateGray>具体劳动和抽象劳动不是各自独立存在的两种劳动或两次劳动，他们在时间上和空间上是统一的，是商品生产者的同一劳动过程不可分割的两个方面</color>
*** <color:DarkSlateGray>具体劳动所反映的是人与自然的关系，是劳动的自然属性</color>
*** <color:DarkSlateGray>抽象劳动所反映的是商品生产者的社会关系，是劳动的社会属性</color>

* <color:DarkSlateGray>劳动力成为商品的两个基本条件</color>
** <color:MidnightBlue>劳动力的定义</color>
*** <color:DarkSlateGray>劳动力是指人的劳动能力，是人的脑力和体力的总和。劳动力的使用即劳动</color>
*** <color:DarkSlateGray>人的劳动是任何社会进行生产都不可或缺的基本条件、基本要素，没有劳动就不可能有人类社会的生存和发展</color>
** <color:MidnightBlue>劳动力成为商品的两个基本条件</color>
*** <color:DarkSlateGray>劳动者在法律上是自由人，能够把自己的劳动力当做商品来支配</color>
*** <color:DarkSlateGray>劳动者没有任何生产资料，没有生活资料来源，因而不得不依靠出卖劳动力为生</color>
** <color:MidnightBlue>劳动力成为商品标志着简单商品生产发展到资本主义商品生产的新阶段</color>
** <color:MidnightBlue>资本家与工人的关系</color>
*** <color:DarkSlateGray>形式上是自由平等的买卖关系</color>
*** <color:DarkSlateGray>实质上是资本家支配和剥削工人的雇佣劳动关系</color>

* <color:DarkSlateGray>垄断</color>
** <color:MidnightBlue>定义</color>
*** <color:DarkSlateGray>少数资本主义大企业为了获得高额利润，通过相互协议或联合，对一个或几个部门商品的生产、销售和价格进行操纵和控制</color>
** <color:MidnightBlue>垄断产生的原因</color>
*** <color:DarkSlateGray>当生产集中发展到相当高的程度，极少数企业就会联合起来，操纵和控制本部门的生产和销售，实行垄断，以获得高额利润</color>
*** <color:DarkSlateGray>企业规模巨大，形成对竞争的限制，也会产生垄断</color>
*** <color:DarkSlateGray>激烈的竞争给竞争各方带来的损失越来越严重，为了避免两败俱伤，企业之间会达成妥协，联合起来，实行垄断</color>

* <color:DarkSlateGray>论述题</color>
** <color:MidnightBlue>实践的本质、形式及相互关系</color>
*** <color:DarkSlateGray>本质：实践是主体借助于一定的工具，有意识、有目的地探索和改造客体的物质活动。人类能动地改造世界的社会性的物质活动</color>
*** <color:DarkSlateGray>特征：客观实在性、主观能动性、社会历史性</color>
*** <color:DarkSlateGray>基本形式——构成社会实践的基本框架</color>
**** <color:Black>物质生产实践：物质生产实践是人类最基本的实践活动，是社会生存发展的基础和前提</color>
**** <color:Black>处理社会关系的实践：社会政治实践是处理各种政治关系的实践</color>
***** <color:Black>关系</color>
****** <color:Black>以上三种实践类型既各具不同的社会功能，又紧密联系在一起</color>
******* <color:Black>物质生产实践是最基本的实践活动，构成全部社会生活的基础</color>
******* <color:Black>社会政治实践和科学文化实践在物质生产实践基础上产生和发展</color>
******** <color:Black>受物质生产实践的制约</color>
******** <color:Black>并对其产生能动地反作用</color>
**** <color:Black>科学文化实验：以探索未知为目的的社会实践。科学文化实践是创造精神文化产品的实践活动</color>
** <color:MidnightBlue>请结合唯物史观原理 论述文化对社会发展的重要作用（文化的作用，科技）</color>
*** <color:DarkSlateGray>文化是社会意识的重要组成部分。文化蕴含着人类的思想智慧，价值追求和审美情趣，是一个国家、一个民族的灵魂。坚定文化自信，是事关国运兴衰、事关文化安全、事关民族精神独立的大问题</color>
*** <color:DarkSlateGray>文化对社会发展的重要作用主要表现在：</color>
**** <color:Black>文化为社会发展提供思想保证。作为一定经济、政治的反映，文化必然发挥维护或批判现实社会的功能，并影响社会发展的方向</color>
**** <color:Black>文化为社会发展提供精神动力。中国特色社会主义文化是凝聚和激励全国各族人民的重要力量</color>
**** <color:Black>文化为社会发展提供智力支持。文化体现着人类认识世界的成果，并对人们改造世界的活动具有智力支持作用</color>
**** <color:Black>文化为社会发展提供凝聚理论。文化的核心是价值观，通过它在社会中占主导地位的价值导向和规范体系，狡猾社会成员，增进社会认同，促进民族意识和精神的形成</color>
** <color:MidnightBlue>结合实践谈一谈为何社会主义事业必须始终坚持无产阶级政党的领导</color>
*** <color:DarkSlateGray>无产阶级是最先进最革命的阶级，肩负着推翻资本主义旧世界、建立社会主义和共产主义新世界的历史使命</color>
*** <color:DarkSlateGray>无产阶级革命是无产阶级进行斗争的最高形式，以建立无产阶级专政的国家为目的</color>
*** <color:DarkSlateGray>无产阶级政党是无产阶级的先锋队，社会主义事业必须始终坚持无产阶级政党的领导</color>
**** <color:Black>社会主义事业的推进不是一个自发的过程，而是一个有组织有领导的自觉地过程</color>
**** <color:Black>无产阶级政党是社会主义事业的组织者和领导力量</color>
***** <color:Black>在社会主义革命、建设、改革事业中，必须始终坚持无产阶级政党即共产党的领导</color>
****** <color:Black>这是无产阶级和人民群众推翻旧社会、建设新社会取得成功的根本保证和关键所在</color>
**** <color:Black>在社会主义国家，共产党是最高政治领导力量</color>
***** <color:Black>只有毫不动摇的坚持和加强党的领导</color>
***** <color:Black>并努力探索和掌握共产党执政规律</color>
***** <color:Black>不断改善党的领导和提高党的执政能力</color>
****** <color:Black>社会主义建设事业才能不断取得新的胜利</color>
** <color:MidnightBlue>请结合辩证否定观 论述该如何正确对待中国传统文化/坚持中国文化的同一/正确对待外来文化和民族文化</color>
*** <color:DarkSlateGray>基本内容：</color>
**** <color:Black>否定是事物的自我否定，是事物内部矛盾运动的结果</color>
**** <color:Black>辩证的否定有两个特点：</color>
***** <color:Black>否定是发展的环节。事物的发展是通过否定实现的</color>
***** <color:Black>否定是联系的环节。新事物对旧事物的否定不是把旧事物中的一切因素完全抛弃，而是否定其中过时的，保留其中合理的，把新旧事物联系起来</color>
**** <color:Black>辩证的否定是扬弃，是既克服又保留。（克服是就发展而言，保留是就联系而言。）克服其消极因素，保留其积极因素</color>
*** <color:DarkSlateGray>意义：</color>
**** <color:Black>坚持辩证否定观就要对一切事物采取分析的态度，反对不加分析的肯定一切或否定一切</color>
***** <color:Black>对待历史文化遗产，既要继承又要批判，既要反对历史虚无主义，又要反对复古主义</color>
***** <color:Black>对待外来文化，既要大胆吸收，又要抵制腐朽，既要反对闭关自守，又要反对全盘西化</color>
** <color:MidnightBlue>根据你对科技的社会作用的理解，在利用科技方面，我们应该如何做到有所为有所不为</color>
*** <color:DarkSlateGray>科学技术作为先进生产力的重要标志，是推动社会文明进步的重要力量</color>
**** <color:Black>对生产方式产生了深刻影响：</color>
***** <color:Black>改变了社会生产力的构成因素</color>
***** <color:Black>改变了人们的劳动形式</color>
***** <color:Black>改变了社会经济结构，特别是导致产业结构发生变革</color>
**** <color:Black>对生活方式产生了巨大的影响：</color>
***** <color:Black>现代科技革命把人们带入了信息时代，要求人们不断更新和充实知识</color>
***** <color:Black>促进了思维方式的改变。人们获得了新的理论知识结构，能够运用新的理论工具和现代化技术手段去研究新课题、新领域</color>
*** <color:DarkSlateGray>正确把握科学技术的社会作用：</color>
**** <color:Black>科学技术能够通过促进经济和社会发展造福于人类，科学技术的作用既受到一定客观条件如社会制度、利益关系的影响，也受到一定主观条件如人们的观念和认识水平的影响</color>
**** <color:Black>科学技术的发展标志着人类改造自然能力的增强，意味着人们能够创造出更多的物质财富，对社会发展有巨大的推动作用</color>
**** <color:Black>但科学技术在运用于社会时所遇到的问题也越来越突出</color>
***** <color:Black>一种情形是对自然规律和人与自然的关系认识不够</color>
***** <color:Black>或缺乏对科学技术消极后果的强有力的控制手段</color>
***** <color:Black>还有一种情形与一定的社会制度有关</color>
****** <color:Black>在资本主义条件下，科学技术常常被资产阶级用作剥削压迫人民的工具</color>
******* <color:Black>并非都能使人摆脱贫困</color>
******* <color:Black>促进人的身心健康发展</color>
****** <color:Black>因而，科学技术有时“表现为异己的、敌对的和统治的权力”</color>
**** <color:Black>正确认识和运用科学技术，首要的就是有合理的社会制度保障科学技术的正确运用，始终坚持使科学技术为人类社会的健康发展服务，让科技为人类造福</color>
** <color:MidnightBlue>实现共产主义是一个漫长的历史过程</color>
*** <color:DarkSlateGray>共产主义的实现是一个十分漫长而且充满艰难曲折的历史过程</color>
**** <color:Black>当代资本主义的灭亡和向社会主义、共产主义的转变也是一个长期的过程</color>
**** <color:Black>社会主义社会的充分发展和向共产主义社会过渡需要很长的历史时期；首先取决于社会主义国家的巩固和发展，取决于这些国家所经历的社会主义建设的历史进程</color>
*** <color:DarkSlateGray>“共产主义渺茫论”的主要论点：在经历十年浩劫之后，中华大地曾经流行过“共产主义渺茫论”，认为“共产主义是地平线，看得见，达不到。”</color>
*** <color:DarkSlateGray>“共产主义渺茫论”是错误的</color>
**** <color:Black>共产主义理想一定能够实现，共产主义社会一定能够变成现实</color>
***** <color:Black>第一，共产主义的理论基础已经在实践中得到验证</color>
***** <color:Black>第二，作为共产主义第一阶段的社会主义制度已经成为现实</color>
***** <color:Black>第三，共产主义作为一种运动，不断改变着世界的面貌</color>
@endmindmap
